---
  - hosts: stack-control
    become: yes
    tasks: 

      - name: mysql permissions
        script: /home/usnik/ansible-git/openstack-automation-using-ansible-CentOS/playbooks/2.keystone/scripts/keystonepre.sh

      - name: install keystone packages
        yum: name={{ item }} state=present update_cache=yes disable_gpg_check=yes update_cache=yes
        with_items:
          - 'openstack-keystone'
          - 'httpd'
          - 'mod_wsgi'

      - name: replace line
        lineinfile: 
          dest: /etc/keystone/keystone.conf
          regexp: '^(.*)connection =(.*)$' 
          line: 'connection = mysql+pymysql://keystone:qaz@controller/keystone'
          backrefs: yes

      # - name: replace line
      #   lineinfile: 
      #     dest: /etc/keystone/keystone.conf
      #     regexp: '^(.*)KEYSTONE_DBPASS =(.*)$' 
      #     line: 'KEYSTONE_DBPASS= "qaz"'
      #     backrefs: yes

      - name: replace line
        lineinfile: 
          dest: /etc/keystone/keystone.conf
          regexp: '^(.*)provider =(.*)$' 
          line: 'provider= fernet'
          backrefs: yes

      - name: copy file to remote machine
        copy: src=/home/usnik/ansible-git/openstack-automation-using-ansible-CentOS/playbooks/2.keystone/scripts/keystone-manage.sh dest=/temp.sh mode=777

      - name: keystone manage
        command: sh /temp.sh >> keystone_manage_output
        ignore_errors: yes

      - name: replace line
        lineinfile: 
          dest: /etc/httpd/conf/httpd.conf
          regexp: '^(.*)ServerName(.*)$' 
          line: 'ServerName controller'
          backrefs: yes

      - name: creating a softlink
        command: ln -s /usr/share/keystone/wsgi-keystone.conf /etc/httpd/conf.d/
        ignore_errors: yes
        
      - name: enable and start httpd.service
        service: name=httpd.service enabled=yes state=started

      - name: exporting in current session
        script: /home/usnik/ansible-git/openstack-automation-using-ansible-CentOS/playbooks/2.keystone/scripts/export.sh

      - name: creating bashrc
        command: touch /root/.bashrc

      - name: exporting system variables
        blockinfile:
          path: /root/.bashrc
          block: |
            export OS_USERNAME=admin
            export OS_PASSWORD=qaz
            export OS_PROJECT_NAME=admin
            export OS_USER_DOMAIN_NAME=Default
            export OS_PROJECT_DOMAIN_NAME=Default
            export OS_AUTH_URL=http://controller:35357/v3
            export OS_IDENTITY_API_VERSION=3


