name: controller
data-dir: /var/lib/etcd
initial-cluster-state: 'new'
initial-cluster-token: 'etcd-cluster-01'
initial-cluster: controller=http://10.0.0.31:2380
initial-advertise-peer-urls: http://10.0.0.31:2380
advertise-client-urls: http://10.0.0.31:2379
listen-peer-urls: http://0.0.0.0:2380
listen-client-urls: http://10.0.0.31:2379