---
  - hosts: stack-control:compute-c
    become: yes
    tasks:
   
         
      - name: refresh dist upgrade yum
        yum: name={{ item }} state=present update_cache=yes disable_gpg_check=yes update_cache=yes
        with_items:
          - 'centos-release-openstack-queens'

      - name: upgrade all packages
        yum:
          name: '*'
          state: latest

      - name: install python-stack client
        yum: name=python-openstackclient state=present update_cache=yes

      - name: install openstack-selinux client
        yum: name=openstack-selinux state=present update_cache=yes