---
  - hosts: stack-control
    become: yes
    tasks:
      
      - name: install mariadb pymysql
        yum: name={{ item }} state=present update_cache=yes disable_gpg_check=yes update_cache=yes
        with_items:
          - 'mariadb-server'
          - 'mariadb'
          - 'python2-PyMySQL'
     
      - name: create openstack.cnf
        file:
          path: /etc/my.cnf.d/openstack.cnf
          state: touch
    
      - name: writing to openstack.cnf
        blockinfile:
          path: /etc/my.cnf.d/openstack.cnf
          block: |
            [mysqld]
            bind-address = 10.0.0.243

            default-storage-engine = innodb
            innodb_file_per_table = on
            max_connections = 4096
            collation-server = utf8_general_ci
            character-set-server = utf8

      - name: enable and start mysql
        service: name=mariadb.service enabled=yes state=started

        