---
  - hosts: stack-control
    become: yes
    tasks: 
      
      - name: running mysql_secure_instrallation
        script: /home/usnik/ansible-git/openstack-automation-using-ansible-CentOS/playbooks/1.Setting_Environment/scripts/mysql_secure_instrallation.sh
