---
  - hosts: stack-control
    become: yes
    tasks:
     


      - name: install memcached
        yum: name={{ item }} state=present update_cache=yes disable_gpg_check=yes update_cache=yes
        with_items:
          - 'memcached'
          - 'python-memcached'



      - name: replace line
        lineinfile: 
          dest: /etc/sysconfig/memcached
          regexp: '^(.*)OPTION="-l 127.0.0.1"(.*)$' 
          line: 'OPTIONS="-l 127.0.0.1,::1,controller"'
          backrefs: yes


      - name: enable and start memcached
        service: name=memcached.service enabled=yes state=started
