---
  - hosts: stack-control
    become: yes
    tasks:
      
      - name: install mariadb pymysql
        yum: name={{ item }} state=present update_cache=yes disable_gpg_check=yes update_cache=yes
        with_items:
          - 'etcd'

      - name: copying etcd.conf
        copy:
          src: /home/usnik/ansible-git/openstack-automation-using-ansible/playbooks/1.Setting_Environment/files/etcd.conf
          dest: /etc/etcd/


      - name: enable and start etcd
        service: name=etcd enabled=yes state=started
